// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2WVqxf6Lw4osDT4FTpaZBFDbAELA5OFk',
    appId: '1:526258335682:web:b4baa3b934064068ac305b',
    messagingSenderId: '526258335682',
    projectId: 'chat-app-3036a',
    authDomain: 'chat-app-3036a.firebaseapp.com',
    storageBucket: 'chat-app-3036a.appspot.com',
    measurementId: 'G-6M7W59BH0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkOcYqfOTI_IyzCDWemGcYSyFMwKlWnAk',
    appId: '1:526258335682:android:f2236dd8dfe8ecc0ac305b',
    messagingSenderId: '526258335682',
    projectId: 'chat-app-3036a',
    storageBucket: 'chat-app-3036a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXKyf2KlKhiTSpu2K7GbkU9GnKt9KRMbI',
    appId: '1:526258335682:ios:593a7e31c275eff2ac305b',
    messagingSenderId: '526258335682',
    projectId: 'chat-app-3036a',
    storageBucket: 'chat-app-3036a.appspot.com',
    iosClientId: '526258335682-qnr6hqm02hh2f2rsg6fsq8ilk8pcqknk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
